# Generated by Django 4.1.1 on 2022-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="Bioqrafiya")),
                (
                    "instagram",
                    models.CharField(max_length=100, verbose_name="Instagram"),
                ),
                ("facebook", models.CharField(max_length=100, verbose_name="Facebook")),
                ("youtube", models.CharField(max_length=100, verbose_name="Youtube")),
                ("linkedin", models.CharField(max_length=100, verbose_name="Linkedin")),
            ],
        ),
    ]
